//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IDProduct { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public string Category { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
    }
}
